const languageOptions = [
    { value: "en", label: "English (English)" },
    { value: "af", label: "Afrikaans (Afrikaans)" },
    { value: "am", label: "አማርኛ (Amharic)" },
    { value: "ar", label: "العَرَبِيَّة (Arabic)" },
    { value: "ar-EG", label: "عربي مصري (Arabic (Egypt))" },
    { value: "ar-MA", label: "العَرَبِيَّة مغربي (Arabic (Morocco))" },
    { value: "ar-SA", label: "العربية السعودية (Arabic (Saudi Arabia))" },
    { value: "az", label: "Azərbaycanca (Azerbaijani)" },
    { value: "bg", label: "Български (Bulgarian)" },
    { value: "bho", label: "भोजपुरी (Bhojpuri)" },
    { value: "bn", label: "বাংলা (Bengali)" },
    { value: "bs", label: "Bosanski (Bosnian)" },
    { value: "ca", label: "Català (Catalan)" },
    { value: "cs", label: "Čeština (Czech)" },
    { value: "da", label: "Dansk (Danish)" },
    { value: "de", label: "Deutsch (German)" },
    { value: "el", label: "Eλληνικά (Greek)" },
    { value: "en-GB", label: "English (United Kingdom)" },
    { value: "es", label: "Español de España (European Spanish)" },
    { value: "es-419", label: "Español de Latinoamérica (Latin American Spanish)" },
    { value: "es-AR", label: "Español (Argentina) (Spanish (Argentina))" },
    { value: "es-MX", label: "Español (México) (Spanish (Mexico))" },
    { value: "et", label: "Eesti (Estonian)" },
    { value: "eu", label: "Euskara (Basque)" },
    { value: "fa", label: "فارسی (Persian)" },
    { value: "fi", label: "Suomeksi (Finnish)" },
    { value: "fil", label: "Filipino (Filipino)" },
    { value: "fr", label: "Français (French)" },
    { value: "fr-CA", label: "Français Canadien (Canadian French)" },
    { value: "gl", label: "Galego (Galician)" },
    { value: "gu", label: "ગુજરાતી (Gujarati)" },
    { value: "he", label: "עברית (Hebrew)" },
    { value: "hi", label: "हिन्दी (Hindi)" },
    { value: "hr", label: "Hrvatski (Croatian)" },
    { value: "hu", label: "Magyar (Hungarian)" },
    { value: "id", label: "Bahasa Indonesia (Indonesian)" },
    { value: "is", label: "Íslenska (Icelandic)" },
    { value: "it", label: "Italiano (Italian)" },
    { value: "ja", label: "日本語 (Japanese)" },
    { value: "kn", label: "ಕನ್ನಡ (Kannada)" },
    { value: "ko", label: "한국어 (Korean)" },
    { value: "lt", label: "Lietuvių (Lithuanian)" },
    { value: "lv", label: "Latviešu (Latvian)" },
    { value: "mk", label: "Македонски (Macedonian)" },
    { value: "ml", label: "മലയാളം (Malayalam)" },
    { value: "mr", label: "मराठी (Marathi)" },
    { value: "ms", label: "Melayu (Malay)" },
    { value: "nb", label: "Norsk (Norwegian)" },
    { value: "ne", label: "नेपाली (Nepali)" },
    { value: "nl", label: "Nederlands (Dutch)" },
    { value: "or", label: "ଓଡ଼ିଆ (Odia)" },
    { value: "pa-IN", label: "ਪੰਜਾਬੀ (Punjabi)" },
    { value: "pa-PK", label: "پنجابی (Punjabi (Naskh))" },
    { value: "pl", label: "Polski (Polish)" },
    { value: "pt-BR", label: "Português do Brasil (Brazilian Portuguese)" },
    { value: "pt-PT", label: "Português (European Portuguese)" },
    { value: "ro", label: "Română (Romanian)" },
    { value: "ru", label: "Русский (Russian)" },
    { value: "sk", label: "Slovenčina (Slovak)" },
    { value: "sl", label: "Slovenski (Slovenian)" },
    { value: "sr", label: "Srpski (Serbian)" },
    { value: "sv", label: "Svenska (Swedish)" },
    { value: "sw", label: "Kiswahili (Swahili)" },
    { value: "ta", label: "தமிழ் (Tamil)" },
    { value: "te", label: "తెలుగు (Telugu)" },
    { value: "th", label: "ภาษาไทย (Thai)" },
    { value: "tr", label: "Türkçe (Turkish)" },
    { value: "uk", label: "Українська (Ukrainian)" },
    { value: "ur", label: "اردو (Urdu)" },
    { value: "vi", label: "Tiếng Việt (Vietnamese)" },
    { value: "zh-CN", label: "简体中文 (Simplified Chinese)" },
    { value: "zh-HK", label: "繁體中文 (香港) (Chinese (Traditional) Hong Kong)" },
    { value: "zh-TW", label: "中文 (Traditional Chinese)" },
    { value: "zu", label: "IsiZulu (Zulu)" },
];

export default languageOptions;